# Используем базу с CUDA для твоей RTX 4090
FROM runpod/pytorch:2.1.0-py3.10-cuda11.8.0-devel-ubuntu22.04

# Ставим FFmpeg и утилиту для скачивания весов нейронки
RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6 wget git && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Ставим библиотеки
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Сразу скачиваем веса Real-ESRGAN и GFPGAN в образ
RUN mkdir -p /app/weights && \
    wget -O /app/weights/RealESRGAN_x4plus.pth https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth && \
    wget -O /app/weights/GFPGANv1.4.pth https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.4.pth

# Копируем шрифт (переименовываем в font.ttf для совместимости с handler.py)
RUN mkdir -p /app/fonts
COPY SoyuzGroteskBold.ttf /app/fonts/font.ttf

# Копируем код обработчика
COPY handler.py .

# Запуск. Убедись, что путь к handler.py верный
CMD [ "python", "-u", "handler.py" ]
